#t Generated by Django 2.0.5 on 2018-05-18 15:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180518_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=datetime.datetime(2018, 5, 18, 15, 27, 36, 817134, tzinfo=utc))),
                ('isActive', models.BooleanField(default=1)),
                ('isDelete', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('logo', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='isActive',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='category',
            name='isDelete',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='isActive',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='post',
            name='isDelete',
            field=models.BooleanField(default=0),
        ),
    ]
