# Generated by Django 2.0.5 on 2018-05-25 16:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180518_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='fbUrl',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='gitUrl',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='inUrl',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='liUrl',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='twUrl',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='updateDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='setting',
            name='logo',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
