# Generated by Django 2.0.5 on 2018-05-26 18:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180525_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('comment', models.CharField(max_length=1000)),
                ('createdDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('isActive', models.BooleanField(default=True)),
                ('isDelete', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
                ('commentReply', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='blog.PostComment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post')),
            ],
        ),
    ]
