# Generated by Django 2.0.5 on 2018-05-28 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_postcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='commentReply',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.PostComment'),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
    ]
