# Generated by Django 2.0.5 on 2018-05-29 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20180528_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcomment',
            name='commentReply',
        ),
        migrations.RemoveField(
            model_name='postcomment',
            name='post',
        ),
        migrations.DeleteModel(
            name='PostComment',
        ),
    ]
