# Generated by Django 2.0.5 on 2018-06-01 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_postcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='commentReply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.PostComment'),
        ),
    ]
