# Generated by Django 2.0.5 on 2018-06-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20180607_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='isDelete',
            field=models.BooleanField(default=False),
        ),
    ]
